import type { Metadata } from "next";
import "@/shared/styles/globals.css";
import {poppins, roboto} from "@/shared/fonts";
import {Header} from "@/components/header/Header";


export const metadata: Metadata = {
  title: "VPN App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
